apiVersion: v1
data:
  nginx.conf: |
    http {
      server {
        listen 8081;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    app: example
  name: example-configmap-1-f84h5gtdk9
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: example
  name: example
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
