apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: FOO
      valueFrom:
        configMapKeyRef:
          name: example-configmap-1
          key: FOO
