apiVersion: v1
data:
  FOO: bar
kind: ConfigMap
metadata:
  annotations:
    app: example
  name: example-configmap-1-59m54fbgh2
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: example
  name: example
  namespace: default
spec:
  containers:
  - env:
    - name: FOO
      valueFrom:
        configMapKeyRef:
          key: FOO
          name: example-configmap-1-59m54fbgh2
    image: nginx
    name: nginx
